// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop__pch.h"
#include "Vtop__Syms.h"
#include "Vtop___024root.h"

// Parameter definitions for Vtop___024root
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__FALL_THROUGH;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_ready__DOT__RESVAL;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_ready__DOT__RESVAL;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_enable__DOT__RESVAL;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_enable__DOT__RESVAL;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_burst__DOT__RESVAL;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_burst__DOT__RESVAL;
constexpr CData/*7:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_burst_len__DOT__RESVAL;
constexpr CData/*7:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_burst_len__DOT__RESVAL;
constexpr CData/*7:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_len__DOT__RESVAL;
constexpr CData/*2:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_size__DOT__RESVAL;
constexpr CData/*3:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_nsaid__DOT__RESVAL;
constexpr CData/*7:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_len__DOT__RESVAL;
constexpr CData/*2:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_size__DOT__RESVAL;
constexpr CData/*3:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_nsaid__DOT__RESVAL;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_ar_handler__DOT__RW;
constexpr CData/*0:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_aw_handler__DOT__RW;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_ready__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_ready__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_ready__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_ready__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_enable__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_enable__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_enable__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_enable__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_burst__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_burst__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_burst__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_burst__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_burst_len__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_burst_len__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_burst_len__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_burst_len__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_addrl__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_addrl__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_addrh__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_addrh__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_len__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_len__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_size__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_size__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_nsaid__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_nsaid__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_addrl__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_addrl__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_addrh__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_addrh__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_len__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_len__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_size__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_size__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_nsaid__DOT__SWACCESS;
constexpr SData/*15:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_nsaid__DOT__wr_en_data_arb__DOT__SWACCESS;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__USER_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__ID_SLV_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__USER_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__AXI4_ADDRESS_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__AXI4_RDATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__AXI4_WDATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__AXI4_ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__AXI4_USER_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__AXI_NUMBYTES;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__BUFF_DEPTH_SLAVE;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__APB_NUM_SLAVES;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__APB_ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__USER_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__BUFFER_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__BUFFER_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__THRESHOLD;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ALM_EMPTY_TH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ALM_FULL_TH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ADDR_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__ADDR_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_aw_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__FifoDepth;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__USER_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__BUFFER_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__BUFFER_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__THRESHOLD;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ALM_EMPTY_TH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ALM_FULL_TH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ADDR_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__ADDR_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_ar_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__FifoDepth;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__USER_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__BUFFER_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__STRB_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__BUFFER_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__THRESHOLD;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ALM_EMPTY_TH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ALM_FULL_TH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ADDR_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__ADDR_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_w_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__FifoDepth;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__USER_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__BUFFER_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__STRB_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__BUFFER_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__THRESHOLD;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ALM_EMPTY_TH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ALM_FULL_TH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ADDR_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__ADDR_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_r_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__FifoDepth;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__ID_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__USER_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__BUFFER_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__BUFFER_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__THRESHOLD;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ALM_EMPTY_TH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ALM_FULL_TH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__ADDR_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__ADDR_DEPTH;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_generic_reader_writer_prog_if__DOT__i_axi2apb_64_32_iopmp__DOT__slave_b_buffer_i__DOT__i_axi_single_slice__DOT__i_fifo__DOT__impl__DOT__i_fifo_v3__DOT__FifoDepth;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__AW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__DBW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_ready__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_ready__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_ready__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_ready__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_enable__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_enable__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_enable__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_enable__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_burst__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_burst__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_burst__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_burst__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_burst_len__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_r_burst_len__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_burst_len__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_control_w_burst_len__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_addrl__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_addrl__DOT__RESVAL;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_addrl__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_addrh__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_addrh__DOT__RESVAL;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_addrh__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_len__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_len__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_size__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_size__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_nsaid__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_ar_cfg_nsaid__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_addrl__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_addrl__DOT__RESVAL;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_addrl__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_addrh__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_addrh__DOT__RESVAL;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_addrh__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_len__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_len__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_size__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_size__DOT__wr_en_data_arb__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_nsaid__DOT__DW;
constexpr IData/*31:0*/ Vtop___024root::dut__DOT__i_generic_reader_writer_top__DOT__i_regmap__DOT__u_aw_cfg_nsaid__DOT__wr_en_data_arb__DOT__DW;


void Vtop___024root___ctor_var_reset(Vtop___024root* vlSelf);

Vtop___024root::Vtop___024root(Vtop__Syms* symsp, const char* v__name)
    : VerilatedModule{v__name}
    , vlSymsp{symsp}
 {
    // Reset structure values
    Vtop___024root___ctor_var_reset(this);
}

void Vtop___024root::__Vconfigure(bool first) {
    (void)first;  // Prevent unused variable warning
}

Vtop___024root::~Vtop___024root() {
}
